PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE iteminfo (
gameID text UNIQUE NOT NULL,
itemName text PRIMARY KEY,
itemImage text NOT NULL,
itemURL text NOT NULL,
itemNatural integer
);
INSERT INTO "iteminfo" VALUES('qg','Drum (Crude Oil)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Crude_Oil)',1);
INSERT INTO "iteminfo" VALUES('rW','Drum (NeoPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(NeoPentane)',0);
INSERT INTO "iteminfo" VALUES('rR','Drum (Naphthalene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Naphthalene)',0);
INSERT INTO "iteminfo" VALUES('rj','Drum (Light Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Light_Naphtha)',0);
INSERT INTO "iteminfo" VALUES('rm','Drum (Light Parrafins)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Light_Parrafins)',0);
INSERT INTO "iteminfo" VALUES('pC','Canister (Butane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Butane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('s9','Drum (Pentane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Pentane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('r2','Drum (Hexane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Hexane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('260','Apple','https://minecraft.gamepedia.com/File:Apple.png','https://polycraft.utdallas.edu/index.php?title=Apple',1);
INSERT INTO "iteminfo" VALUES('392','Potato','https://minecraft.gamepedia.com/File:Potato.png','https://polycraft.utdallas.edu/index.php?title=Potato',1);
INSERT INTO "iteminfo" VALUES('115','Nether Wart','https://minecraft.gamepedia.com/File:Nether_Wart.png','https://polycraft.utdallas.edu/index.php?title=Nether_Wart',1);
INSERT INTO "iteminfo" VALUES('81','Cactus','https://minecraft.gamepedia.com/File:Cactus.png','https://polycraft.utdallas.edu/index.php?title=Cactus',1);
INSERT INTO "iteminfo" VALUES('82','Reeds','https://minecraft.gamepedia.com/File:Reeds.png','https://polycraft.utdallas.edu/index.php?title=Reeds',1);
INSERT INTO "iteminfo" VALUES('296','Wheat','https://minecraft.gamepedia.com/File:Wheat.png','https://polycraft.utdallas.edu/index.php?title=Wheat',1);
INSERT INTO "iteminfo" VALUES('391','Carrot','https://minecraft.gamepedia.com/File:Carrot.png','https://polycraft.utdallas.edu/index.php?title=Carrot',1);
INSERT INTO "iteminfo" VALUES('h4','Vial (Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Naphtha)',0);
INSERT INTO "iteminfo" VALUES('ms','Beaker (Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Naphtha)',0);
INSERT INTO "iteminfo" VALUES('rQ','Drum (Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Naphtha)',0);
INSERT INTO "iteminfo" VALUES('rl','Drum (Light Olefins)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Light_Olefins)',0);
INSERT INTO "iteminfo" VALUES('pu','Drum (Benzene-Toluene-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Benzene-Toluene-Xylene)',0);
INSERT INTO "iteminfo" VALUES('18','Leaves','https://minecraft.gamepedia.com/File:Leaves.png','https://polycraft.utdallas.edu/index.php?title=Leaves',1);
INSERT INTO "iteminfo" VALUES('tE','Drum (Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Xylene)',0);
INSERT INTO "iteminfo" VALUES('iS','Vial (Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Xylene)',0);
INSERT INTO "iteminfo" VALUES('og','Beaker (Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Xylene)',0);
INSERT INTO "iteminfo" VALUES('gz','Vial (Light Olefins)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Light_Olefins)',0);
INSERT INTO "iteminfo" VALUES('lX','Beaker (Light Olefins)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Light_Olefins)',0);
INSERT INTO "iteminfo" VALUES('g8','Vial (Gas Oil)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Gas_Oil)',0);
INSERT INTO "iteminfo" VALUES('qU','Drum (Gas Oil)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Gas_Oil)',0);
INSERT INTO "iteminfo" VALUES('lw','Beaker (Gas Oil)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Gas_Oil)',0);
INSERT INTO "iteminfo" VALUES('fu','Vial (Crude Oil)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Crude_Oil)',0);
INSERT INTO "iteminfo" VALUES('kS','Beaker (Crude Oil)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Crude_Oil)',0);
INSERT INTO "iteminfo" VALUES('ha','Vial (NeoPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(NeoPentane)',0);
INSERT INTO "iteminfo" VALUES('my','Beaker (NeoPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(NeoPentane)',0);
INSERT INTO "iteminfo" VALUES('h5','Vial (Naphthalene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Naphthalene)',0);
INSERT INTO "iteminfo" VALUES('mt','Beaker (Naphthalene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Naphthalene)',0);
INSERT INTO "iteminfo" VALUES('gx','Vial (Light Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Light_Naphtha)',0);
INSERT INTO "iteminfo" VALUES('lV','Beaker (Light Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Light_Naphtha)',0);
INSERT INTO "iteminfo" VALUES('gA','Vial (Light Parrafins)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Light_Parrafins)',0);
INSERT INTO "iteminfo" VALUES('lY','Beaker (Light Parrafins)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Light_Parrafins)',0);
INSERT INTO "iteminfo" VALUES('eQ','Flask (Butane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Butane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('ke','Cartridge (Butane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_cartridge.png','https://polycraft.utdallas.edu/index.php?title=Cartridge_(Butane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('hn','Vial (Pentane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Pentane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('mL','Beaker (Pentane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Pentane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('gg','Vial (Hexane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Hexane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('lE','Beaker (Hexane Isomers)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Hexane_Isomers)',0);
INSERT INTO "iteminfo" VALUES('eI','Vial (Benzene-Toluene-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Benzene-Toluene-Xylene)',0);
INSERT INTO "iteminfo" VALUES('k6','Beaker (Benzene-Toluene-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Benzene-Toluene-Xylene)',0);
INSERT INTO "iteminfo" VALUES('f','Tar Sand','https://minecraft.gamepedia.com/File:Tar_Sand.png','https://polycraft.utdallas.edu/index.php?title=Tar_Sand',1);
INSERT INTO "iteminfo" VALUES('g','Shale','https://minecraft.gamepedia.com/File:Shale.png','https://polycraft.utdallas.edu/index.php?title=Shale',1);
INSERT INTO "iteminfo" VALUES('j','Bitumen','https://minecraft.gamepedia.com/File:Bitumen.png','https://polycraft.utdallas.edu/index.php?title=Bitumen',0);
INSERT INTO "iteminfo" VALUES('17','Block of Bitumen','https://minecraft.gamepedia.com/File:Block_of_Bitumen.png','https://polycraft.utdallas.edu/index.php?title=Block_of_Bitumen',0);
INSERT INTO "iteminfo" VALUES('326','Water Bucket','https://minecraft.gamepedia.com/File:Water_Bucket.png','https://polycraft.utdallas.edu/index.php?title=Water_Bucket',1);
INSERT INTO "iteminfo" VALUES('3m','Bucket (Crude Oil)','https://minecraft.gamepedia.com/File:Bucket.png','https://polycraft.utdallas.edu/index.php?title=Bucket_(Crude_Oil)',1);
INSERT INTO "iteminfo" VALUES('rC','Canister (Methane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Methane)',0);
INSERT INTO "iteminfo" VALUES('rU','Drum (n-Butane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(n-Butane)',0);
INSERT INTO "iteminfo" VALUES('s1','Drum (n-Pentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(n-Pentane)',0);
INSERT INTO "iteminfo" VALUES('lv','Beaker (Fruit Brandy)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Fruit_Brandy)',0);
INSERT INTO "iteminfo" VALUES('oc','Beaker (Vodka)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Vodka)',0);
INSERT INTO "iteminfo" VALUES('lx','Beaker (Gin)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Gin)',0);
INSERT INTO "iteminfo" VALUES('nQ','Beaker (Tequila)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Tequila)',0);
INSERT INTO "iteminfo" VALUES('ne','Beaker (Rum)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Rum)',0);
INSERT INTO "iteminfo" VALUES('oe','Beaker (Whiskey)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Whiskey)',0);
INSERT INTO "iteminfo" VALUES('kF','Beaker (Carrot Wine)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Carrot_Wine)',0);
INSERT INTO "iteminfo" VALUES('sB','Canister (Propylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Propylene)',0);
INSERT INTO "iteminfo" VALUES('pt','Drum (Benzene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Benzene)',0);
INSERT INTO "iteminfo" VALUES('11Q','Vial (Isoprene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Isoprene)',0);
INSERT INTO "iteminfo" VALUES('s4','Drum (o-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(o-Xylene)',0);
INSERT INTO "iteminfo" VALUES('hi','Vial (o-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(o-Xylene)',0);
INSERT INTO "iteminfo" VALUES('mG','Beaker (o-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(o-Xylene)',0);
INSERT INTO "iteminfo" VALUES('hP','Flask (Propylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Propylene)',0);
INSERT INTO "iteminfo" VALUES('nd','Cartridge (Propylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_cartridge.png','https://polycraft.utdallas.edu/index.php?title=Cartridge_(Propylene)',0);
INSERT INTO "iteminfo" VALUES('gt','Vial (Kerosene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Kerosene)',0);
INSERT INTO "iteminfo" VALUES('rf','Drum (Kerosene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Kerosene)',0);
INSERT INTO "iteminfo" VALUES('lR','Beaker (Kerosene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Kerosene)',0);
INSERT INTO "iteminfo" VALUES('gQ','Flask (Methane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Methane)',0);
INSERT INTO "iteminfo" VALUES('me','Cartridge (Methane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_cartridge.png','https://polycraft.utdallas.edu/index.php?title=Cartridge_(Methane)',0);
INSERT INTO "iteminfo" VALUES('h8','Vial (n-Butane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(n-Butane)',0);
INSERT INTO "iteminfo" VALUES('mw','Beaker (n-Butane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(n-Butane)',0);
INSERT INTO "iteminfo" VALUES('hf','Vial (n-Pentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(n-Pentane)',0);
INSERT INTO "iteminfo" VALUES('mD','Beaker (n-Pentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(n-Pentane)',0);
INSERT INTO "iteminfo" VALUES('eH','Vial (Benzene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Benzene)',0);
INSERT INTO "iteminfo" VALUES('k5','Beaker (Benzene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Benzene)',0);
INSERT INTO "iteminfo" VALUES('125','Beaker (Salt Water)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Salt_Water)',1);
INSERT INTO "iteminfo" VALUES('r0','Drum (Heavy Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Heavy_Naphtha)',0);
INSERT INTO "iteminfo" VALUES('rk','Drum (Light Naphthenes)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Light_Naphthenes)',0);
INSERT INTO "iteminfo" VALUES('qC','Canister (Ethane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Ethane)',0);
INSERT INTO "iteminfo" VALUES('rc','Drum (IsoButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(IsoButane)',0);
INSERT INTO "iteminfo" VALUES('rd','Drum (IsoPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(IsoPentane)',0);
INSERT INTO "iteminfo" VALUES('oO','Drum (2-MethylPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(2-MethylPentane)',0);
INSERT INTO "iteminfo" VALUES('lA','Beaker (Glycolic Acid)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Glycolic_Acid)',0);
INSERT INTO "iteminfo" VALUES('ge','Vial (Heavy Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Heavy_Naphtha)',0);
INSERT INTO "iteminfo" VALUES('lC','Beaker (Heavy Naphtha)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Heavy_Naphtha)',0);
INSERT INTO "iteminfo" VALUES('qH','Canister (Ethylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Ethylene)',0);
INSERT INTO "iteminfo" VALUES('tl','Drum (Toluene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Toluene)',0);
INSERT INTO "iteminfo" VALUES('s8','Drum (p-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(p-Xylene)',0);
INSERT INTO "iteminfo" VALUES('hm','Vial (p-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(p-Xylene)',0);
INSERT INTO "iteminfo" VALUES('mK','Beaker (p-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(p-Xylene)',0);
INSERT INTO "iteminfo" VALUES('fV','Flask (Ethylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Ethylene)',0);
INSERT INTO "iteminfo" VALUES('lj','Cartridge (Ethylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_cartridge.png','https://polycraft.utdallas.edu/index.php?title=Cartridge_(Ethylene)',0);
INSERT INTO "iteminfo" VALUES('fG','Vial (Diesel)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Diesel)',0);
INSERT INTO "iteminfo" VALUES('qs','Drum (Diesel)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(Diesel)',0);
INSERT INTO "iteminfo" VALUES('l4','Beaker (Diesel)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Diesel)',0);
INSERT INTO "iteminfo" VALUES('le','Cartridge (Ethane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_cartridge.png','https://polycraft.utdallas.edu/index.php?title=Cartridge_(Ethane)',0);
INSERT INTO "iteminfo" VALUES('gy','Vial (Light Naphthenes)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Light_Naphthenes)',0);
INSERT INTO "iteminfo" VALUES('lW','Beaker (Light Naphthenes)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Light_Naphthenes)',0);
INSERT INTO "iteminfo" VALUES('fQ','Flask (Ethane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Ethane)',0);
INSERT INTO "iteminfo" VALUES('gq','Vial (IsoButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(IsoButane)',0);
INSERT INTO "iteminfo" VALUES('lO','Beaker (IsoButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(IsoButane)',0);
INSERT INTO "iteminfo" VALUES('gr','Vial (IsoPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(IsoPentane)',0);
INSERT INTO "iteminfo" VALUES('lP','Beaker (IsoPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(IsoPentane)',0);
INSERT INTO "iteminfo" VALUES('e2','Vial (2-MethylPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(2-MethylPentane)',0);
INSERT INTO "iteminfo" VALUES('jq','Beaker (2-MethylPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(2-MethylPentane)',0);
INSERT INTO "iteminfo" VALUES('iz','Vial (Toluene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(Toluene)',0);
INSERT INTO "iteminfo" VALUES('nX','Beaker (Toluene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(Toluene)',0);
INSERT INTO "iteminfo" VALUES('12','Sand','https://minecraft.gamepedia.com/File:Sand.png','https://polycraft.utdallas.edu/index.php?title=Sand',1);
INSERT INTO "iteminfo" VALUES('13','Gravel','https://minecraft.gamepedia.com/File:Gravel.png','https://polycraft.utdallas.edu/index.php?title=Gravel',1);
INSERT INTO "iteminfo" VALUES('325','Bucket','https://minecraft.gamepedia.com/File:Bucket.png','https://polycraft.utdallas.edu/index.php?title=Bucket',1);
INSERT INTO "iteminfo" VALUES('sz','Canister (Propane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Propane)',0);
INSERT INTO "iteminfo" VALUES('a1','Canister (Nitrogen)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_canister.png','https://polycraft.utdallas.edu/index.php?title=Canister_(Nitrogen)',0);
INSERT INTO "iteminfo" VALUES('oU','Drum (3-MethylPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(3-MethylPentane)',0);
INSERT INTO "iteminfo" VALUES('rA','Drum (m-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(m-Xylene)',0);
INSERT INTO "iteminfo" VALUES('gO','Vial (m-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(m-Xylene)',0);
INSERT INTO "iteminfo" VALUES('mc','Beaker (m-Xylene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(m-Xylene)',0);
INSERT INTO "iteminfo" VALUES('nb','Cartridge (Propane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_cartridge.png','https://polycraft.utdallas.edu/index.php?title=Cartridge_(Propane)',0);
INSERT INTO "iteminfo" VALUES('hN','Flask (Propane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Propane)',0);
INSERT INTO "iteminfo" VALUES('6d','Flask (Nitrogen)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_flask.png','https://polycraft.utdallas.edu/index.php?title=Flask_(Nitrogen)',0);
INSERT INTO "iteminfo" VALUES('e8','Vial (3-MethylPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(3-MethylPentane)',0);
INSERT INTO "iteminfo" VALUES('jw','Beaker (3-MethylPentane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(3-MethylPentane)',0);
INSERT INTO "iteminfo" VALUES('2t','Bag (Anthracene)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_bag.png','https://polycraft.utdallas.edu/index.php?title=Bag_(Anthracene)',0);
INSERT INTO "iteminfo" VALUES('oE','Drum (2,3-DiMethylButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(2,3-DiMethylButane)',0);
INSERT INTO "iteminfo" VALUES('dS','Vial (2,3-DiMethylButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(2,3-DiMethylButane)',0);
INSERT INTO "iteminfo" VALUES('jg','Beaker (2,3-DiMethylButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_beaker.png','https://polycraft.utdallas.edu/index.php?title=Beaker_(2,3-DiMethylButane)',0);
INSERT INTO "iteminfo" VALUES('19O','Vanadium Pentoxide Catalyst','https://minecraft.gamepedia.com/File:Vanadium_Pentoxide_Catalyst.png','https://polycraft.utdallas.edu/index.php?title=Vanadium_Pentoxide_Catalyst',0);
INSERT INTO "iteminfo" VALUES('oD','Drum (2,2-DiMethylButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_drum.png','https://polycraft.utdallas.edu/index.php?title=Drum_(2,2-DiMethylButane)',0);
INSERT INTO "iteminfo" VALUES('dR','Vial (2,2-DiMethylButane)','https://polycraft.utdallas.edu/index.php?title=File:Vessel_vial.png','https://polycraft.utdallas.edu/index.php?title=Vial_(2,2-DiMethylButane)',0);
COMMIT;
